### ISSUE TITLE
|In Orphanet DB file en_product6.xml the field OrphaNumber changed into OrphaCode 

### ISSUE THREAD

**Issue by erinijapranckeviciene** [buske/compbio-toolkit#1]
The beautiful `get-orphanet-gene-xls.cgi`  crashes since recently, because in the source _**en_product6.xml**_ the field name **OrphaNumber** changed into **OrphaCode** : line 30.

`disorder_orpha = disorder.find('OrphaNumber').text =>  disorder_orpha = disorder.find('OrphaCode').text`

I corrected in my cloned version and it is working as before.  
Since I am pulling this code in my scripts and I believe there could be more users of this super-useful code, it would be great if this small discrepancy  could be fixed in github. 

Many thanks for your work!

**Comment by buske** [comment]
@erinijapranckeviciene Thank you so much for creating this issue to let me know! I've gone ahead and committed the change you suggested. Thanks again.
